### ISSUE TITLE
OBJ Exporting Issue

### ISSUE THREAD

**Issue by RhysSterling** [morris/vstools#1]
Exporting to OBJ breaks the model's UV Map beyond repair.

Evidenced by; http://puu.sh/tnfxu/9d1ff7f525.png

**Comment by morris** [comment]
Hi, i've just updated dependencies - the OBJ exporter works now, however you'll need to flip textures vertically. I wonder why though, since the OBJ exporter is entirely taken from three.js' original source. Thanks for reporting 🍻
