### ISSUE TITLE
Obj exporter issue.

### ISSUE THREAD

**Issue by JusticeSword** [morris/vstools#3]
The model veiwer is fantastic and works a treat for visual reference, but i am having trouble with exporting the models as obj, i click the exporter button but alas a mere quick white flash and nothing occurs, i am using the most recent download repository and opening in chrome.

**Comment by MrQuetch** [comment]
I've been wondering about this, too. I might even write a custom exporter that does just that. I've been looking at the documentation for Vagrant Story map files, and they don't seem too difficult to me.

**Comment by morris** [comment]
yeah it was broken. should work a lot better now :)
