### ISSUE TITLE
RawGit has been sunsetted, alternative soon needed for online use

### ISSUE THREAD

**Issue by HeyItsLollie** [morris/vstools#4]
Posted October 8, 2018 at https://rawgit.com/
> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
>
>GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
>
>If you're currently using RawGit, please stop using it as soon as you can.

Ultimately low priority, as this viewer can be downloaded and used offline, but figured it was worth reporting.

**Comment by morris** [comment]
Hi! Good point, I've just switched it over to GitHub Pages. Thanks :)
