### ISSUE TITLE
[Feature Request] Viewer options, eg: Wireframe overlay, vertex color toggle

### ISSUE THREAD

**Issue by HeyItsLollie** [morris/vstools#5]
It'd be a real boon to have some model inspection features in the viewer, especially for maps.
For example: Wireframe overlay for geometry, or toggles to enable/disable vertex colors or textures.

**Comment by morris** [comment]
Thanks for the interest :) I will look into it. First there's some chores to do (e.g. update Three.js) but I will see what I can do!

**Comment by morris** [comment]
just pushed a few updates, including wireframe and vertex color and texture toggles. have fun :)

**Comment by HeyItsLollie** [comment]
The new features are perfect, thank you so much!
